### ISSUE TITLE
A few questions about the details

### ISSUE THREAD

**Issue by ashawkey** [Gorilla-Lab-SCUT/Fantasia3D#1]
Hi, congratulations on the great work! The results are really impressive.
I have a few questions regarding the implementation details, and wish you could help:

1. In Section 4.2, how do you calculate $\tilde n$ from $(n, o)$? Is it by concatenating since you directly downsample $\tilde n$ to 4-channel latent code? I also wonder the reason behind this step, since normal + visibility mask seems unrelated to the latent code.
2. For DMTet's network $\Psi(v_i)$, do you use any positional encoding on the input vertices? Or do you only use 3-channel xyz so the MLP is just 3-32-4?
3. In each iteration you use a large batch size of 24 cameras, could this be different from only using a  single camera per iteration?
4. Do you use any direction-augmented prompt like appending `front/side/back/top view`?

Finally, is there an expected date for code releasing? 
Thanks in advance!

**Comment by ARuiChen** [comment]
Hi, @ashawkey! We are incredibly grateful for your stable-dreamfusion project. Part of our code is implemented based on your work. I will answer your questions in the following.
1. Yes, it is. During the experiment, we observe that directly inputting rendered images to stable diffusion resulted in the network producing results that match the text description in visual effects, and it tends to fall into local optima and have very rough geometry, leading to fraudulent outputs. Therefore, we need features that could respond to geometric information, such as normals and masks. We choose to use normals and masks as latent code because the range of normalized normal values is exactly (-1,1), which is the data range required for latent space diffusion, and masks can reflect the contour information of objects. It is worth noting that in the early stage of optimization, we can quickly transform the ellipse into a rough target shape by concatenating the mask and normal and sending the downsampling results to the stable diffusion (without using an encoder at this time). In the later stage of optimization, using only high-resolution normals can increase geometric details, and an encoder is required for this phase.
2. We use hash-grid positional encoding for both the geometry and appearance modeling.
3. The larger the batch size used, the faster the results can converge. With large batches, the geometry updates can be monitored from a global perspective as much as possible during each iteration.
4. For objects with obvious directionality, we use the appending prompt like front/side/back view. We avoid using the "top view" prompt, as it can hinder the convergence of results. Conversely, for objects without clear directionality, we discard the direction-augmented prompt altogether.
5. Due to other things, we are currently unable to provide an accurate timeline for publishing the code. However, we will make every effort to organize and release the code as soon as possible.

I hope the answers provided above can be helpful to you. Thank you for your attention to our work!

**Comment by ashawkey** [comment]
Thanks for the detailed explanation! It solves my questions clearly. 
Looking forward to the code releasing!

**Comment by Inn1917** [comment]
Well, I wonder whether you tested representing the DMTet sdf value and vertex deformation with a tensor instead of an MLP mentioned in the paper. if so, can it produce plausible result in geometry learning?

**Comment by ARuiChen** [comment]
> Well, I wonder whether you tested representing the DMTet sdf value and vertex deformation with a tensor instead of an MLP mentioned in the paper. if so, can it produce plausible result in geometry learning?

Sorry for the late reply! We once optimized the SDF value and vertex deformation without using MLP prediction and found that the mesh quickly diverged.

**Comment by Inn1917** [comment]
Truly polite indeed :)
Recently I tried the hash grid MLP but achieved poor results...If possible I would like to ask for some advices.
The first problem is the stability of the mesh optimization process. If I increase the weight of sds loss, the mesh will be empty after a few iteration. Have you encountered such circumtance?
The second is the quality of the result. With low sds loss weight the optimization can go on, but the resulting mesh is always quite noisy regardless of different regularization I tried. Would you like to share some important detail of the geometry optimization process?
Great thanks!

**Comment by ARuiChen** [comment]
> Truly polite indeed :) Recently I tried the hash grid MLP but achieved poor results...If possible I would like to ask for some advices. The first problem is the stability of the mesh optimization process. If I increase the weight of sds loss, the mesh will be empty after a few iteration. Have you encountered such circumtance? The second is the quality of the result. With low sds loss weight the optimization can go on, but the resulting mesh is always quite noisy regardless of different regularization I tried. Would you like to share some important detail of the geometry optimization process? Great thanks!

You can try this <a href="https://github.com/ashawkey/fantasia3d.unofficial">preliminary reproduction</a> of our work. 😉

**Comment by Inn1917** [comment]
Thanks for the notification!
