### ISSUE TITLE
about pbr configs

### ISSUE THREAD

**Issue by mdarhdarz** [Gorilla-Lab-SCUT/Fantasia3D#14]
I note that all the apperance configs set 1&3 channel of ks as 0. Is this mean the metalness is disgarded?

**Comment by ARuiChen** [comment]
Hi, @mdarhdarz! Just because the example provided does not happen to be set by me. If you believe that the appearance described in the text has metalness, you can set the range of metalness. It depends on your expectations and experience. For instance,  the range can be set as follow for the text "A golden goblet" :
```python
"ks_min" : [0, 0.08, 0.5],
"ks_max" : [0, 0.5, 0.98],
``` 
or
```python
"ks_min" : [0, 0.08, 1],
"ks_max" : [0, 0.5, 1],
``` 
BTW, you need to relight the object after training to visualize the specular effect by changing the HDR map. The part of this hasn't been uploaded yet.
