### ISSUE TITLE
Awesome results! But I have a few questions:

### ISSUE THREAD

**Issue by ReRadioActivity** [Gorilla-Lab-SCUT/Fantasia3D#3]
1. How long does it take to generate a result? And how much VRAM does it require?
2. Were you able to fix the multi-face Janus problem?
3. Will the resulting generation be a point cloud or a polygonal mesh (or optional)?
4. Can it work with any other custom SD-based models, like Dreambooths and LORAs?
Thanks in advance.

**Comment by ARuiChen** [comment]
Hi, @ReRadioActivity!
1. As explained in the paper’s implementation details, our method is optimized on 8 Nvidia RTX 3090 GPUs for 3000 iterations (about 25 minutes) for geometry modeling and 2000 iterations (about 20 minutes) for appearance modeling. We found that the larger the batch size, the faster the results converge, so we utilized the full capacity of the 3090 graphics memory. However, either 4 or 6 Nvidia RTX 3090 GPUs are sufficient for generating objects without obvious directionality. We haven't tried generating 3D content with fewer GPUs yet. The optimization time mentioned above is for the majority of the generated examples. In fact, many examples only require 30~35 minutes in total (including the generation of geometry and appearance) to converge. 
2. Actually, we have used the camera sampling strategy mentioned in the supplementary materials to alleviate this problem. The main idea of this sampling strategy is to ensure that the optimization process can be observed from a global perspective and to emphasize the role of an appending directional prompt like front/side/back view. Because of the pseudo-random nature of uniform sampling, simply uniformly sampling each camera pose from an azimuth angle of 0 to 360 degrees may result in camera poses that are too close to each other and cannot provide a global view (which may increase the chance of multiple faces). 
3. Our method can directly obtain a polygonal mesh with PBR material.
4. We have not experimented with any other custom SD-based models, so I cannot comment on their usefulness.

I hope the above explanations can address your issue! Thank you for your interest in our work!
