### ISSUE TITLE
Weighting Strategy

### ISSUE THREAD

**Issue by jaidevshriram** [Gorilla-Lab-SCUT/Fantasia3D#35]
Hey! Thanks for making the code public, the results are great! I'm wondering if you could share some light on the weightings strategy used. Specifically, how did you arrive at $$w(t) = \sigma^2 \sqrt{1-\sigma^2}$$

I'm working on SDS in a different scenario and considering borrowing some ideas from Fantasia3D so would appreciate any insights! I noticed that in the README you provide some tips on the weighting strategy implemented in the code, but any explanation/guess on the behaviour would be useful. Thanks!

https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/a9d0ac1076dcc85a797bbbbb200bd5ef56aa117b/geometry/dlmesh.py#L120-L130

**Comment by ARuiChen** [comment]
The strategy weight is a hyperparameter. The parameter, i.g. $\omega(t) =\sigma ^{2}$, used in DreamFusion is an equation that increases as the time step t increases. This may apply to volume rendering, but it is not as suitable for surface rendering. In practice, I found that using the weight of the original version will make the rendered image over-saturated and lack detail and realism. This may be caused by the excessive weight of large t. Therefore, I want to use the weight that gradually decreases with the increase of t, so I get the strategy 0.
As for the proposal of strategy 1, I have observed that in some cases, using strategy 0 can produce a more realistic appearance, but often strange colors appear. Therefore, I would like to switch to a more suitable weight. I realized that the score function is essentially a directional gradient pointing towards the target distribution, and it can transform with the estimated noise, so I came up with Strategy 1, i.g.  
```math
 s(z_{t};t) =-\frac{1}{\sigma _{t}}\varepsilon(z_{t};t),
``` 
where $s$ is the score function. In practice, I found that it can effectively alleviate the problem of strange colors when used in conjunctions with the time step range of [0.02, 0.98].

**Comment by jaidevshriram** [comment]
Thanks for the detailed response! Those are some interesting observations - I'll try them out. I'm wondering if you also tried out the gradient from score jacobian chaining instead - I think the expression for that will resemble strategy 1 slightly.
